version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000" 

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:5000" 
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "${MONGODB_PORT}:27017" 

